### PR TITLE
#16 in range returns incorrect registered port

### LINKED ISSUE #16: InRange returns incorrect registered ports
**Describe the bug**

Some range registered ports are returned incorrectly

**To Reproduce**

```
make build
./httpref ports 16404
16384-16403
[... redacted ...]
```

**Expected behavior**

The range returned should include the port requested. Like so:

```
./httpref ports 16404
16403-16472
[... redacted ...]
```

**Desktop**

System Version: macOS 10.15.5 (19F101)  Kernel Version: Darwin 19.5.0

**Additional context**

The httpref.InRange function should change a condition from `if code >= parts[0] || code <= parts[len(parts)-1]` to `if code >= parts[0] && code <= parts[len(parts)-1]` to correctly identify the range.

I would like to submit a PR fixing this issue and improving the test case to ensure that the expected range is returned. Is that okay with you?

### PR DESCRIPTION
**Pull request by jan-carreras**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #16 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Running existing tests
- [x] Created new tests

Increased the coverage to 100%

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have rebased my branch to include the latest changes from `master`

### CODE REVIEW

File: registered-ports.go [hunk 1]
```diff
@@ -822,7 +822,7 @@ UDP         - Unspecified
 https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Registered_ports`,
 	},
 	{
-		Name: "1560–1590",
+		Name: "1560-1590",
```
Comment (jan-carreras) [inline registered-ports.go:825]: From the commit message:

> The middle dash character "-" was not the ASCII 0xD2 but some other representation: 0xE28093 preventing the correct comparison in the code logic and ignoring the record

non-ascii-char

File: httpref_test.go [hunk 2]
```diff
@@ -86,3 +87,13 @@ func TestReferences_Titles(t *testing.T) {
 	n := Statuses.Titles()
 	assert.Equal(t, 5, len(n))
 }
+
```
Comment (jan-carreras) [inline httpref_test.go:104]: Add test case to ensure that both WellKnownPort and RegisteredPorts do not include funny characters. Valid ones:

* 8080
* 8080-8081

File: httpref.go [hunk 3]
```diff
@@ -70,7 +70,7 @@ func (r References) InRange(code string) References {
 
 		if strings.Contains(v.Name, "-") {
 			parts := strings.Split(v.Name, "-")
-			if code >= parts[0] || code <= parts[len(parts)-1] {
+			if code >= parts[0] && code <= parts[len(parts)-1] {
```
Comment (jan-carreras) [inline httpref.go:69]: The port being searched must be between the range. The operand was incorrect.

File: httpref_test.go [hunk 4]
```diff
@@ -30,20 +30,34 @@ func TestReferences_ByName(t *testing.T) {
 }
 
 func TestReferences_InRange(t *testing.T) {
```
Comment (jan-carreras) [inline httpref_test.go:32]: Added more test with its expected result, not only the cardinality

File: httpref_test.go [hunk 5]
```diff
@@ -30,20 +30,34 @@ func TestReferences_ByName(t *testing.T) {
...
+			got := RegisteredPorts.InRange(tt.having)
+			if len(got) != 1 {
 				t.Errorf("References.InRange() = %v, want %v", len(got), 1)
 			}
+			if got[0].Name != tt.expect {
+				t.Errorf("References.InRange()[0] = %v, want %v", got[0].Name, tt.expect)
+			}
 		})
 	}
+
```
Comment (jan-carreras) [inline httpref_test.go:54]: Add a failing test, searching for a port that is not valid, thus should not return anything. Increases coverage.

File: httpref.go [hunk 6]
```diff
@@ -64,10 +64,6 @@ func (r References) ByName(code string) References {
 // InRange attempts to find a numeric in a range in the Name field
 func (r References) InRange(code string) References {
 	for _, v := range r {
-		if v.Name == code {
```
Comment (jan-carreras) [inline httpref.go:67]: As explained in the commit message:

> The results were inconsistent since References are not sorted by single-port first and wide port ranges may match before single port ones. This is not a breaking change since the logic of InRange being used in the app checks first for specific ports

This logic is, at least, misleading. Depending on the order of the rules on the `structs` of ports, the return may be one or the other. See for example the rule for the port `19150`. It matches the rule `10000-20000` (line 9484 of registered-ports) instead of the more specific rule of `19150` (line 10970 from registered-ports) because the most general rule appears first.

Since it's a non breaking change and the code is not currently being used, I would remove it to achieve a 100% coverage of the project.

File: httpref_test.go (hunk 2 above)
Comment (jan-carreras) [reply httpref_test.go:104]: (Note to my future self: always select a range of code relevant to the comment)

File: httpref_test.go (hunk 4 above)
Comment (jan-carreras) [reply httpref_test.go:32]: (Note to my future self: always select a range of code relevant to the comment)

File: registered-ports.go (hunk 1 above)
Comment (jan-carreras) [reply registered-ports.go:825]: The test failing before doing the replacements of chars in files:

```
=== RUN   TestPortsConsistencyValidation
    httpref_test.go:96: Invalid port format: 71–74
    httpref_test.go:96: Invalid port format: 225–241
    httpref_test.go:96: Invalid port format: 249–255
    httpref_test.go:96: Invalid port format: 1011–1020
    httpref_test.go:96: Invalid port format: 1560–1590
    httpref_test.go:96: Invalid port format: 1582–1583
    httpref_test.go:96: Invalid port format: 2222–2226
    [... redacted... 48 offending rules in total]
```

**Comment by dnnrly** [comment]
Dont sweat the self review too much. That checkbox is there to make sure people have given their code a once over before the formally submit the PR.

For me, it's important that you made the right fix and the tests pass.

Do you think it's ready?

**Comment by jan-carreras** [comment]
Hi @dnnrly , yes hi think it's ready.

It's my first contribution to an Open Source project and I'm doing the same I usually do at work — I'll be less verbose in future PRs 👍

**Comment by dnnrly** [comment]
Wow, I am honoured that you chose this project to be your first contribution. It shows that you review code at work and it's very much appreciated.

As for this PR, I will resolve all of the comments you've made so don't think that I'm ignoring them. I am away from any computers this week so it may take a little while to take it all in.

File: httpref_test.go [hunk 7]
```diff
@@ -29,20 +30,34 @@ func TestReferences_ByName(t *testing.T) {
...
-		"5988",
-		"5989",
+	tests := []struct {
+		having string
+		expect string
+	}{
+		{having: "19150", expect: "10000-20000"},
+		{having: "16406", expect: "10000-20000"},
+		{having: "5988", expect: "5988-5989"},
+		{having: "5989", expect: "5988-5989"},
```
Comment (dnnrly) [inline httpref_test.go:40]: I like this change. It says what we're testing more succinctly.

File: httpref_test.go [hunk 8]
```diff
@@ -86,3 +101,13 @@ func TestReferences_Titles(t *testing.T) {
 	n := Statuses.Titles()
 	assert.Equal(t, 5, len(n))
 }
+
+func TestPortsConsistencyValidation(t *testing.T) {
```
Comment (dnnrly) [inline httpref_test.go:105]: I was going to ask if this test is necessary BUT I think it actually specifies the contract for naming port mappings. Well spotted!

File: registered-ports.go (hunk 1 above)
Comment (dnnrly) [reply registered-ports.go:825]: Aaaaand this is why the previous test was necessary. :smile:

**Comment by jan-carreras** [comment]
Thanks for taking the time to review my comments, I really appreciate it. My first contribution 👏 👏 I'm so happy.
